package com.mav.rpgbuilder.legends;

public enum MoralAlignment {
    HONOR_BOUND,
    HONOR_AMONG_THIEVES,
    BALANCE_KEEPER,
    FREEDOM_SEEKER,
    ORDER_ARCHITECT,
    AMBITION_DRIVEN,
    CARNAGE_LUST,
    SHADOW_LOYALIST,
    CORRUPTION_WARPED,
    RIGHTEOUS_CRUELTY,
    CALCULATED_EVIL


}
